---
- name: Pull JAR from S3
  hosts: app
  become: true
  vars_files:
    - setup_vars.yml
  tasks:
    - name: Download JAR 
      aws_s3:
        bucket: "{{ bucket_name }}"
        object: "{{ bucket_key }}"
        dest: "/tmp/{{ object }}"
        mode: get
        # aws_access_key: <Insert Key here> 
        # aws_secret_key: <Inser Key here>
    - name: Check if application is already running
      shell: "pgrep {{ object }}; echo $?"
      register: application_running
      ignore_errors: true
    - debug: 
        msg: "Application running: {{ application_running }}"
    - name: Kill application if it is running # NEVER DO THIS IN A PROD APPLICATION
      command: "pkill {{ object }}"
      when: application_running == 1
    - name: Startup application
      command: "nohup java -jar /tmp/{{ object }} &"
      async: 1
      poll: 0